print(" Hidayat Azka ")
print(312210374)
print("=============")

# Luas dan Keliling lingkaran
d = float(input(" Masukkan diameter lingkaran : ")) 
r = (d/2)
phi = 3.14
L = phi * (r * r)
K = (phi * d)
print(" diketahui : ")
print(" diameter = ",d,"cm")
print(" jari-jari = ",r,"cm")
print(" Phi = ",phi)
print(" ditanya Luas Lingkaran dan Keliling Lingkaran ?")
print(" L = phi x r x r ")
print(" L = ",phi," x ",r," x ",r)
print(" K = phi x d")
print(" K = ",phi," x ",d)
print(" Luas lingkaran adalah = ",L,"cm")
print(" Keliling Lingkaran adalah = ",K,"cm")